language: python
sudo: false
python: 2.7
env:
    - TOX_ENV=flake8
    - TOX_ENV=py27-django18
    - TOX_ENV=py34-django18
    - TOX_ENV=py27-djangomaster
    - TOX_ENV=py34-djangomaster
matrix:
    allow_failures:
        - env: TOX_ENV=flake8
        - env: TOX_ENV=py34-django18
        - env: TOX_ENV=py27-djangomaster
        - env: TOX_ENV=py34-djangomaster
install:
    - pip install tox
script:
    - tox -e $TOX_ENV
