language: python
sudo: false
python:
    - 3.6
env:
    matrix:
        - TOX_ENV=py27-django110
        - TOX_ENV=py27-django111
        - TOX_ENV=flake8
        - TOX_ENV=py34-django110
        - TOX_ENV=py34-django111
        - TOX_ENV=py34-django20
        - TOX_ENV=py36-django110
        - TOX_ENV=py36-django111
        - TOX_ENV=py36-django20
install:
    - pip install tox-travis
script:
    - tox -e $TOX_ENV
