# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-16 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citeIt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='author',
            field=models.CharField(help_text="Author's name formatted Last, First Middle", max_length=255),
        ),
        migrations.AlterField(
            model_name='citation',
            name='degree_level',
            field=models.ForeignKey(help_text='Type of degree', on_delete=django.db.models.deletion.CASCADE, to='citeIt.DegreeLevel'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='granting_institution',
            field=models.ForeignKey(help_text='Institution awarding Degree', on_delete=django.db.models.deletion.CASCADE, to='citeIt.Institution'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='initial_article',
            field=models.CharField(blank=True, help_text='Initial Article (The, A)', max_length=20, verbose_name='Initital Article'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='local_call_no',
            field=models.CharField(blank=True, max_length=200, verbose_name='Local Call Number'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='pagination',
            field=models.IntegerField(help_text='Number of pages formatted as number <em>55</em> <br />Note: the pp is added by the system later '),
        ),
        migrations.AlterField(
            model_name='citation',
            name='title',
            field=models.TextField(help_text='Title (omit initial article)'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='withers_thesis_number',
            field=models.IntegerField(blank=True, help_text='Thesis Number', verbose_name="Withers' Thesis Number"),
        ),
        migrations.AlterField(
            model_name='citation',
            name='year',
            field=models.IntegerField(help_text='Year degree was awarded, formatted as <em>yyyy</em>'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(help_text='Locations should be in the format of <em>Country > State > County > Township</em>', max_length=255),
        ),
    ]
